# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29ddd896d4e4f5d60bfe62729181de527277970f1a73e9ae763055a0600126bfb66fc928e9943952e6850f7dca69524511f8b96409a4174967caf2e9ca4310f8

test:
  secret_key_base: 2d4a624a26843d96e418d321481ea641b5ba8de581e496a1fda378f052a94419422fb90fef799ac5ae8b10df5e1bd100291e624e643f5b35bd245a068b7d01f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
